name: 'Mats Shadow&Light'
favicon: null
layout_spectrum: 0.74063
typography_spectrum: 0.48989
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#111111'
    - '#555555'
    - '#fcfdfd'
    - '#848484'
    - '#9e9e9e'
  brandStrength: 1
  lightness: 0.45371387456543744
  saturation: 0.5091192512772977
  rhythmicContrast: 0.3690617468673736
purpose: []
